[package]
name = "marcus"
version = "0.1.0"
edition = "2021"

[dependencies]

[features]
default = [
  "perft",
]
perft = []
stats = []

[profile.release]
lto = "fat"
codegen-units = 1

[profile.test]
opt-level = 3
