[changelog]
header = ""
body = """
{% for group, commits in commits | group_by(attribute="group") %}
    #### {{ group | upper_first }}
    {% for commit in commits %}
        - {% if commit.breaking %}[**breaking**] {% endif %}{{ commit.message | upper_first }}\
    {% endfor %}
{% endfor %}
"""
trim = true
