name: Main
on:
  push:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          default: true
          components: clippy
      - name: Lint
        run: cargo clippy -- -D warnings

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          default: true
      - name: Bench
        run: cargo bench
      - name: Test
        run: cargo test

  coverage:
    name: Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          default: true
      - name: Install dependencies
        run: cargo install cargo-tarpaulin
      - name: Cleanup
        run: cargo clean
      - name: Measure
        run: cargo tarpaulin --out Xml
      - name: Upload
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true

  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - { target: aarch64-linux-android, name: marcus_android_aarch64, src_file_name: marcus, dst_file_name: marcus_android_aarch64 }
          - { target: x86_64-unknown-linux-gnu, name: marcus_linux_x86_64, src_file_name: marcus, dst_file_name: marcus_linux_x86_64 }
          - { target: x86_64-pc-windows-gnu, name: marcus_windows_x86_64, src_file_name: marcus.exe, dst_file_name: marcus_windows_x86_64.exe }
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          default: true
          override: true
      - name: Install dependencies
        run: |
          cargo install cross
          rustup target add ${{ matrix.target }}
      - name: Build
        run: cross build --release --target=${{ matrix.target }}
      - name: Rename artifact
        run: mv target/${{ matrix.target }}/release/${{ matrix.src_file_name }} ${{ matrix.dst_file_name }}
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.name }}
          path: ${{ matrix.dst_file_name }}
          if-no-files-found: error

  build_macos:
    name: Build (MacOS)
    runs-on: macos-latest
    strategy:
      matrix:
        include:
          - { target: aarch64-apple-darwin, name: marcus_macos_aarch64, src_file_name: marcus, dst_file_name: marcus_macos_aarch64 }
          - { target: x86_64-apple-darwin, name: marcus_macos_x86_64, src_file_name: marcus, dst_file_name: marcus_macos_x86_64 }
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          target: ${{ matrix.target }}
          default: true
          override: true
      - name: Build
        run: cargo build --release --target=${{ matrix.target }}
      - name: Rename artifact
        run: mv target/${{ matrix.target }}/release/${{ matrix.src_file_name }} ${{ matrix.dst_file_name }}
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.name }}
          path: ${{ matrix.dst_file_name }}
          if-no-files-found: error

  release:
    name: Release
    needs: [ test, coverage, build ]
    runs-on: ubuntu-latest
    steps:
      - name: Full checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          path: ~/artifacts/
      - name: Generate changelog
        id: git-cliff
        uses: orhun/git-cliff-action@v2
        with:
          config: cliff.toml
          args: --verbose --unreleased --latest
        env:
          OUTPUT: CHANGELOG.md
      - name: Upload changelog
        uses: actions/upload-artifact@v2
        with:
          name: CHANGELOG.md
          path: "${{ steps.git-cliff.outputs.changelog }}"
          if-no-files-found: error
      - name: Combine release notes
        run: |
          echo "### Downloads" >> notes.txt
          echo "- [Android (aarch64)](https://github.com/codingjerk/marcus/releases/download/v${{ github.run_number }}/marcus_android_aarch64)" >> notes.txt
          echo "- [Linux (x86_64)](https://github.com/codingjerk/marcus/releases/download/v${{ github.run_number }}/marcus_linux_x86_64)" >> notes.txt
          echo "- [MacOS (aarch64)](https://github.com/codingjerk/marcus/releases/download/v${{ github.run_number }}/marcus_macos_aarch64)" >> notes.txt
          echo "- [MacOS (x86_64)](https://github.com/codingjerk/marcus/releases/download/v${{ github.run_number }}/marcus_macos_x86_64)" >> notes.txt
          echo "- [Windows (x86_64)](https://github.com/codingjerk/marcus/releases/download/v${{ github.run_number }}/marcus_windows_x86_64.exe)" >> notes.txt
          echo "### Changelog" >> notes.txt
          cat "${{ steps.git-cliff.outputs.changelog }}" >> notes.txt
      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          name: Nightly v${{ github.run_number }}
          tag_name: v${{ github.run_number }}
          body_path: notes.txt
          prerelease: true
          fail_on_unmatched_files: true
          files: |
            /home/runner/artifacts/**
